curl https://maimaidx.jp/maimai-mobile/img/rating_base_bronze.png -o 12000.png
curl https://maimaidx.jp/maimai-mobile/img/rating_base_silver.png -o 13000.png
curl https://maimaidx.jp/maimai-mobile/img/rating_base_gold.png -o 14000.png
curl https://maimaidx.jp/maimai-mobile/img/rating_base_platinum.png -o 14500.png
curl https://maimaidx.jp/maimai-mobile/img/rating_base_rainbow.png -o 15000.png
curl https://maimaidx.jp/maimai-mobile/img/rating_base_purple.png -o 10000.png
curl https://maimaidx.jp/maimai-mobile/img/rating_base_red.png -o 7000.png
curl https://maimaidx.jp/maimai-mobile/img/rating_base_orange.png -o 4000.png
curl https://maimaidx.jp/maimai-mobile/img/rating_base_normal.png -o 0.png
curl https://maimaidx.jp/maimai-mobile/img/rating_base_green.png -o 2000.png
curl https://maimaidx.jp/maimai-mobile/img/rating_base_blue.png -o 1000.png